Repository alpacahq/alpaca-trade-api-csharp, pull requests merged in 2024-09, with the labels that each got.

#751 Dependencies update (Dependabot)
  Alpaca.Markets.Extensions.Tests/Alpaca.Markets.Extensions.Tests.csproj
  Alpaca.Markets.Extensions/packages.lock.json
  Alpaca.Markets.Tests/Alpaca.Markets.Tests.csproj
  Alpaca.Markets/Alpaca.Markets.csproj
  Alpaca.Markets/packages.lock.json
  UsageExamples/UsageExamples.csproj
Labels: dependencies

#754 Bump xunit from 2.9.0 to 2.9.2 (#356)
  Alpaca.Markets.Extensions.Tests/Alpaca.Markets.Extensions.Tests.csproj
  Alpaca.Markets.Tests/Alpaca.Markets.Tests.csproj
Labels: dependencies, .NET

#755 Update AccountActivitiesRequest.cs
  Alpaca.Markets/Parameters/AccountActivitiesRequest.cs
Labels: bug
